<?php
// database/seeders/ProductSeeder.php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Bebidas
            [
                'code' => 'BEB001',
                'name' => 'Coca Cola 500ml',
                'description' => 'Gaseosa Coca Cola botella 500ml',
                'cost_price' => 120.00,
                'sale_price' => 180.00,
                'stock' => 50,
                'min_stock' => 10,
                'is_active' => true,
            ],
            [
                'code' => 'BEB002',
                'name' => 'Coca Cola 2.25L',
                'description' => 'Gaseosa Coca Cola botella 2.25 litros',
                'cost_price' => 280.00,
                'sale_price' => 420.00,
                'stock' => 30,
                'min_stock' => 8,
                'is_active' => true,
            ],
            [
                'code' => 'BEB003',
                'name' => 'Sprite 500ml',
                'description' => 'Gaseosa Sprite botella 500ml',
                'cost_price' => 115.00,
                'sale_price' => 175.00,
                'stock' => 45,
                'min_stock' => 10,
                'is_active' => true,
            ],
            [
                'code' => 'BEB004',
                'name' => 'Fanta 500ml',
                'description' => 'Gaseosa Fanta naranja botella 500ml',
                'cost_price' => 115.00,
                'sale_price' => 175.00,
                'stock' => 40,
                'min_stock' => 10,
                'is_active' => true,
            ],
            [
                'code' => 'BEB005',
                'name' => 'Agua Mineral 500ml',
                'description' => 'Agua mineral sin gas',
                'cost_price' => 80.00,
                'sale_price' => 130.00,
                'stock' => 100,
                'min_stock' => 20,
                'is_active' => true,
            ],
            [
                'code' => 'BEB006',
                'name' => 'Cerveza Quilmes 1L',
                'description' => 'Cerveza Quilmes litro',
                'cost_price' => 350.00,
                'sale_price' => 550.00,
                'stock' => 60,
                'min_stock' => 15,
                'is_active' => true,
            ],
            [
                'code' => 'BEB007',
                'name' => 'Vino Tinto 750ml',
                'description' => 'Vino tinto común',
                'cost_price' => 450.00,
                'sale_price' => 700.00,
                'stock' => 25,
                'min_stock' => 5,
                'is_active' => true,
            ],
            [
                'code' => 'BEB008',
                'name' => 'Jugo Baggio 1L',
                'description' => 'Jugo Baggio multifruta 1 litro',
                'cost_price' => 180.00,
                'sale_price' => 280.00,
                'stock' => 35,
                'min_stock' => 8,
                'is_active' => true,
            ],

            // Snacks y Golosinas
            [
                'code' => 'SNK001',
                'name' => 'Lays Clásicas 150g',
                'description' => 'Papas fritas Lays clásicas',
                'cost_price' => 220.00,
                'sale_price' => 350.00,
                'stock' => 40,
                'min_stock' => 10,
                'is_active' => true,
            ],
            [
                'code' => 'SNK002',
                'name' => 'Doritos 150g',
                'description' => 'Doritos nachos queso',
                'cost_price' => 230.00,
                'sale_price' => 360.00,
                'stock' => 35,
                'min_stock' => 10,
                'is_active' => true,
            ],
            [
                'code' => 'SNK003',
                'name' => 'Pepitos 55g',
                'description' => 'Galletitas Pepitos con chips de chocolate',
                'cost_price' => 140.00,
                'sale_price' => 220.00,
                'stock' => 60,
                'min_stock' => 15,
                'is_active' => true,
            ],
            [
                'code' => 'SNK004',
                'name' => 'Oreo 118g',
                'description' => 'Galletitas Oreo clásicas',
                'cost_price' => 180.00,
                'sale_price' => 280.00,
                'stock' => 50,
                'min_stock' => 12,
                'is_active' => true,
            ],
            [
                'code' => 'SNK005',
                'name' => 'Alfajor Jorgito',
                'description' => 'Alfajor Jorgito simple',
                'cost_price' => 90.00,
                'sale_price' => 150.00,
                'stock' => 80,
                'min_stock' => 20,
                'is_active' => true,
            ],
            [
                'code' => 'SNK006',
                'name' => 'Alfajor Milka',
                'description' => 'Alfajor Milka triple',
                'cost_price' => 180.00,
                'sale_price' => 280.00,
                'stock' => 45,
                'min_stock' => 12,
                'is_active' => true,
            ],
            [
                'code' => 'SNK007',
                'name' => 'Chocolate Milka 100g',
                'description' => 'Tableta Milka leche 100g',
                'cost_price' => 320.00,
                'sale_price' => 480.00,
                'stock' => 30,
                'min_stock' => 8,
                'is_active' => true,
            ],
            [
                'code' => 'SNK008',
                'name' => 'Caramelos Sugus',
                'description' => 'Caramelos Sugus surtidos x50',
                'cost_price' => 250.00,
                'sale_price' => 380.00,
                'stock' => 25,
                'min_stock' => 5,
                'is_active' => true,
            ],
            [
                'code' => 'SNK009',
                'name' => 'Chicles Beldent',
                'description' => 'Chicles Beldent menta x10',
                'cost_price' => 120.00,
                'sale_price' => 190.00,
                'stock' => 70,
                'min_stock' => 15,
                'is_active' => true,
            ],
            [
                'code' => 'SNK010',
                'name' => 'Maní Salado 100g',
                'description' => 'Maní con sal',
                'cost_price' => 150.00,
                'sale_price' => 240.00,
                'stock' => 40,
                'min_stock' => 10,
                'is_active' => true,
            ],

            // Cigarrillos
            [
                'code' => 'CIG001',
                'name' => 'Marlboro Box',
                'description' => 'Cigarrillos Marlboro caja x20',
                'cost_price' => 850.00,
                'sale_price' => 1200.00,
                'stock' => 100,
                'min_stock' => 20,
                'is_active' => true,
            ],
            [
                'code' => 'CIG002',
                'name' => 'Philips Morris Box',
                'description' => 'Cigarrillos PM caja x20',
                'cost_price' => 800.00,
                'sale_price' => 1150.00,
                'stock' => 90,
                'min_stock' => 20,
                'is_active' => true,
            ],
            [
                'code' => 'CIG003',
                'name' => 'Camel Box',
                'description' => 'Cigarrillos Camel caja x20',
                'cost_price' => 780.00,
                'sale_price' => 1100.00,
                'stock' => 85,
                'min_stock' => 18,
                'is_active' => true,
            ],

            // Productos de almacén
            [
                'code' => 'ALM001',
                'name' => 'Pan Lactal',
                'description' => 'Pan lactal Bimbo grande',
                'cost_price' => 280.00,
                'sale_price' => 420.00,
                'stock' => 20,
                'min_stock' => 5,
                'is_active' => true,
            ],
            [
                'code' => 'ALM002',
                'name' => 'Leche Larga Vida 1L',
                'description' => 'Leche La Serenísima entera',
                'cost_price' => 320.00,
                'sale_price' => 480.00,
                'stock' => 40,
                'min_stock' => 10,
                'is_active' => true,
            ],
            [
                'code' => 'ALM003',
                'name' => 'Huevos x12',
                'description' => 'Maple de huevos blancos x12',
                'cost_price' => 450.00,
                'sale_price' => 650.00,
                'stock' => 25,
                'min_stock' => 5,
                'is_active' => true,
            ],
            [
                'code' => 'ALM004',
                'name' => 'Aceite Girasol 900ml',
                'description' => 'Aceite de girasol común',
                'cost_price' => 380.00,
                'sale_price' => 550.00,
                'stock' => 30,
                'min_stock' => 8,
                'is_active' => true,
            ],
            [
                'code' => 'ALM005',
                'name' => 'Azúcar 1kg',
                'description' => 'Azúcar común 1kg',
                'cost_price' => 280.00,
                'sale_price' => 420.00,
                'stock' => 35,
                'min_stock' => 8,
                'is_active' => true,
            ],
            [
                'code' => 'ALM006',
                'name' => 'Sal Fina 500g',
                'description' => 'Sal fina de mesa',
                'cost_price' => 120.00,
                'sale_price' => 190.00,
                'stock' => 40,
                'min_stock' => 10,
                'is_active' => true,
            ],
            [
                'code' => 'ALM007',
                'name' => 'Arroz 1kg',
                'description' => 'Arroz blanco largo fino',
                'cost_price' => 350.00,
                'sale_price' => 520.00,
                'stock' => 28,
                'min_stock' => 6,
                'is_active' => true,
            ],
            [
                'code' => 'ALM008',
                'name' => 'Fideos Secos 500g',
                'description' => 'Fideos secos tirabuzón',
                'cost_price' => 220.00,
                'sale_price' => 330.00,
                'stock' => 45,
                'min_stock' => 10,
                'is_active' => true,
            ],
            [
                'code' => 'ALM009',
                'name' => 'Mayonesa 500g',
                'description' => 'Mayonesa Hellmanns',
                'cost_price' => 420.00,
                'sale_price' => 620.00,
                'stock' => 22,
                'min_stock' => 5,
                'is_active' => true,
            ],
            [
                'code' => 'ALM010',
                'name' => 'Tomate Triturado 520g',
                'description' => 'Tomate triturado lata',
                'cost_price' => 180.00,
                'sale_price' => 280.00,
                'stock' => 50,
                'min_stock' => 12,
                'is_active' => true,
            ],

            // Higiene y limpieza
            [
                'code' => 'HIG001',
                'name' => 'Papel Higiénico x4',
                'description' => 'Papel higiénico Higienol x4',
                'cost_price' => 380.00,
                'sale_price' => 560.00,
                'stock' => 35,
                'min_stock' => 8,
                'is_active' => true,
            ],
            [
                'code' => 'HIG002',
                'name' => 'Jabón Tocador x3',
                'description' => 'Jabón de tocador Dove x3',
                'cost_price' => 420.00,
                'sale_price' => 620.00,
                'stock' => 28,
                'min_stock' => 6,
                'is_active' => true,
            ],
            [
                'code' => 'HIG003',
                'name' => 'Shampoo 400ml',
                'description' => 'Shampoo Sedal 400ml',
                'cost_price' => 550.00,
                'sale_price' => 800.00,
                'stock' => 20,
                'min_stock' => 5,
                'is_active' => true,
            ],
            [
                'code' => 'HIG004',
                'name' => 'Detergente 500ml',
                'description' => 'Detergente líquido Magistral',
                'cost_price' => 320.00,
                'sale_price' => 480.00,
                'stock' => 25,
                'min_stock' => 6,
                'is_active' => true,
            ],
            [
                'code' => 'HIG005',
                'name' => 'Lavandina 1L',
                'description' => 'Lavandina común 1 litro',
                'cost_price' => 180.00,
                'sale_price' => 280.00,
                'stock' => 30,
                'min_stock' => 8,
                'is_active' => true,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}